#!/usr/bin/env python
import os
import sys

cwd = os.getcwd()
sys.path.insert(0,cwd)

# this import must come after the above or
# reading tiddlywebconfig.py will fail
from tiddlyweb.manage import handle

if __name__ == '__main__':
    handle(sys.argv)
