#!/usr/bin/python

"""
A quick script to post a TiddlyWiki file on local disk to a
bag on a (possibly) remote TiddlyWeb server.

Arg 1 is the URL of the bag. Arg 2 is the path of the wiki file.
"""

import sys
import codecs
import httplib2

def run(url, filename):
    f = codecs.open(filename, encoding='utf-8', errors='replace')
    wikitext = f.read()
    f.close()
    wikitext = wikitext.encode('utf-8')
    http = httplib2.Http()
    response, content = http.request(url, method='POST',
            body=wikitext, headers={'Content-Type': 'text/x-tiddlywiki'})
    print response['status']
    print content

if __name__ == '__main__':
    run(sys.argv[1], sys.argv[2])

